wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.2
    code_path: code/wandb
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
batchSize:
  desc: null
  value: 3575
domain_powers:
  desc: null
  value: null
learningRate:
  desc: null
  value: 0.0012966696646672343
progress_rate:
  desc: null
  value: 0.2
